// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen_main
void ui_Screen_main_screen_init(void);
lv_obj_t * ui_Screen_main;
lv_obj_t * ui_Panel_temp;
lv_obj_t * ui_sensor_sen5x_temperature;
lv_obj_t * ui_Slider_temp;
lv_obj_t * ui_Panel_pm;
lv_obj_t * ui_sensor_sen5x_pm2p5;
lv_obj_t * ui_sensor_data_pm25;
lv_obj_t * ui_Panel_voc;
lv_obj_t * ui_sensor_sen5x_voc;
lv_obj_t * ui_sensor_data_voc;
lv_obj_t * ui_Panel_humi;
lv_obj_t * ui_sensor_sen5x_humi;
lv_obj_t * ui_sensor_data_humi;
lv_obj_t * ui____initial_actions0;

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_main);
}
