// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_main_screen_init(void)
{
    ui_Screen_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen_main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_temp = lv_obj_create(ui_Screen_main);
    lv_obj_set_width(ui_Panel_temp, 109);
    lv_obj_set_height(ui_Panel_temp, 359);
    lv_obj_set_x(ui_Panel_temp, -116);
    lv_obj_set_y(ui_Panel_temp, 3);
    lv_obj_set_align(ui_Panel_temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_temp, lv_color_hex(0xF1D3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_temp, lv_color_hex(0xC7BCA1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel_temp, lv_color_hex(0xC7BCA1), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_temp, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_sensor_sen5x_temperature = lv_label_create(ui_Panel_temp);
    lv_obj_set_width(ui_sensor_sen5x_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_sen5x_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_sen5x_temperature, 0);
    lv_obj_set_y(ui_sensor_sen5x_temperature, -130);
    lv_obj_set_align(ui_sensor_sen5x_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_sen5x_temperature, "Temperature");

    ui_Slider_temp = lv_slider_create(ui_Panel_temp);
    lv_slider_set_range(ui_Slider_temp, 0, 40);
    lv_slider_set_value(ui_Slider_temp, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_temp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_temp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_temp, 22);
    lv_obj_set_height(ui_Slider_temp, 267);
    lv_obj_set_x(ui_Slider_temp, 0);
    lv_obj_set_y(ui_Slider_temp, 19);
    lv_obj_set_align(ui_Slider_temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider_temp, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_bg_img_src(ui_Slider_temp, &ui_img_indicator_ver_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Slider_temp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider_temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider_temp, lv_color_hex(0x65647C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_temp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider_temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider_temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider_temp, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider_temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel_pm = lv_obj_create(ui_Screen_main);
    lv_obj_set_width(ui_Panel_pm, 180);
    lv_obj_set_height(ui_Panel_pm, 70);
    lv_obj_set_x(ui_Panel_pm, 108);
    lv_obj_set_y(ui_Panel_pm, -137);
    lv_obj_set_align(ui_Panel_pm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_pm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_pm, lv_color_hex(0x8B7E74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_pm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_pm, lv_color_hex(0x8B7E74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_pm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor_sen5x_pm2p5 = lv_label_create(ui_Panel_pm);
    lv_obj_set_width(ui_sensor_sen5x_pm2p5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_sen5x_pm2p5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_sen5x_pm2p5, -45);
    lv_obj_set_y(ui_sensor_sen5x_pm2p5, 6);
    lv_obj_set_align(ui_sensor_sen5x_pm2p5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_sen5x_pm2p5, "PM2.5");

    ui_sensor_data_pm25 = lv_label_create(ui_Panel_pm);
    lv_obj_set_width(ui_sensor_data_pm25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_data_pm25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_data_pm25, 0);
    lv_obj_set_y(ui_sensor_data_pm25, 8);
    lv_obj_set_align(ui_sensor_data_pm25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_data_pm25, "NA");

    ui_Panel_voc = lv_obj_create(ui_Screen_main);
    lv_obj_set_width(ui_Panel_voc, 180);
    lv_obj_set_height(ui_Panel_voc, 70);
    lv_obj_set_x(ui_Panel_voc, 107);
    lv_obj_set_y(ui_Panel_voc, 1);
    lv_obj_set_align(ui_Panel_voc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_voc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_voc, lv_color_hex(0xC7BCA1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_voc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_voc, lv_color_hex(0x8B7E74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_voc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Panel_voc, lv_color_hex(0x8B7E74), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_voc, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_sensor_sen5x_voc = lv_label_create(ui_Panel_voc);
    lv_obj_set_width(ui_sensor_sen5x_voc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_sen5x_voc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_sen5x_voc, -45);
    lv_obj_set_y(ui_sensor_sen5x_voc, 4);
    lv_obj_set_align(ui_sensor_sen5x_voc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_sen5x_voc, "voc");

    ui_sensor_data_voc = lv_label_create(ui_Panel_voc);
    lv_obj_set_width(ui_sensor_data_voc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_data_voc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_data_voc, 0);
    lv_obj_set_y(ui_sensor_data_voc, 8);
    lv_obj_set_align(ui_sensor_data_voc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_data_voc, "NA");

    ui_Panel_humi = lv_obj_create(ui_Screen_main);
    lv_obj_set_width(ui_Panel_humi, 180);
    lv_obj_set_height(ui_Panel_humi, 70);
    lv_obj_set_x(ui_Panel_humi, 106);
    lv_obj_set_y(ui_Panel_humi, 124);
    lv_obj_set_align(ui_Panel_humi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_humi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_humi, lv_color_hex(0xC7BCA1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_humi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_humi, lv_color_hex(0x8B7E74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_humi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Panel_humi, lv_color_hex(0x8B7E74), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_humi, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_sensor_sen5x_humi = lv_label_create(ui_Panel_humi);
    lv_obj_set_width(ui_sensor_sen5x_humi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_sen5x_humi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_sen5x_humi, -45);
    lv_obj_set_y(ui_sensor_sen5x_humi, 4);
    lv_obj_set_align(ui_sensor_sen5x_humi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_sen5x_humi, "Humi");

    ui_sensor_data_humi = lv_label_create(ui_Panel_humi);
    lv_obj_set_width(ui_sensor_data_humi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor_data_humi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_data_humi, 0);
    lv_obj_set_y(ui_sensor_data_humi, 8);
    lv_obj_set_align(ui_sensor_data_humi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensor_data_humi, "NA");

}
